[project]
name = "KRONOS"
version = "0.1.0"
description = "Foundation model for multiplex spatial proteomic images"
readme = "README.md"
requires-python = ">=3.9"

authors = [
    { name = "Muhammad Shaban", email = "mshaban@bwh.harvard.edu" },
    { name = "Faisal Mahmood", email = "faisalmahmood@bwh.harvard.edu" }
]
dependencies = [
    "numpy>=1.26.4",
    "torch>=2.0.0",
    "xformers>=0.0.18",
    "huggingface_hub>=0.28.1",
    "torchvision>=0.23.0",
    "wandb>=0.25.1",
]

[project.optional-dependencies]
tutorials = [
    "jupyter",
    "ipywidgets",
    "pandas",
    "h5py",
    "scipy",
    "tifffile",
    "matplotlib",
    "scikit-learn",
    "scikit-image",
    "optuna",
]

[build-system]

requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["kronos"]
